insert or ignore into course values (1, 'CIS 9240', 'Sustainability and Information Technology');
insert or ignore into course values (2, 'CIS 9310', 'Object-Oriented Programming I');
insert or ignore into course values (3, 'CIS 9556', 'Risk Management Systems');
insert or ignore into course values (4, 'CIS 9557', 'Business Intelligence');
insert or ignore into course values (5, 'STA 9708', 'Applied Statistical Analysis for Business Decisions');
insert or ignore into course values (6, 'ACC 9110', 'Financial Accounting');
insert or ignore into course values (7, 'ACC 9110', 'Systems Analysis and Design');
insert or ignore into course values (8, 'MKT 9785', 'Digital Marketing Strategy');
insert or ignore into course values (9, 'MKT 9738', 'Web Analytics and Intelligence');
insert or ignore into course values (10, 'MKT 9726', 'Direct Marketing I: Strategy and Tactics');
insert or ignore into course values (11, 'RES 9940', 'Real Estate Marketing');
insert or ignore into book values (1, 'The Living Company', 'Arie De Geus', '2nd', 1234);
insert or ignore into book values (2, 'The Principles of Sustainability', 'Simon Dresner', '1st', 2943);
insert or ignore into book values (3, 'Going Green Together - How to Align Employees with Green Strategies', 'Frank Roettgers', '3rd', 5072);
insert or ignore into book values (4, 'Object-Oriented Programming', 'Peter Coad ', '7th', 5345);
insert or ignore into book values (5, 'Object Oriented Methods', 'Ian Graham', '4th', 6342);
insert or ignore into book values (6, 'Value at Risk: The New Benchmark for Managing Financial Risk', 'Philippe Jorion', '3rd', 63432);
insert or ignore into book values (7, 'Business Intelligence Guidebook: From Data Integration to Analytics', 'Risk Sherman', '3rd', 8342);
insert or ignore into book values (8, 'Business Intelligence Strategy: A Practical Guide for Achieving BI Excellence', 'John Boyer', '4th', 8324);
insert or ignore into book values (9, 'Applied Statistics for Business and Management using Microsoft Excel', 'Linda Herkenhoff and John Fogli', '3rd', 27533);
insert or ignore into book values (10, 'Applied Statistics in Business and Economics', 'David Doane and Lori Seward', '5th', 6223);
insert or ignore into book values (11, 'Principles of Applied Statistics', 'Professor D. R. Cox and Professor Christl A. Donnelly', '3rd', 5231);
insert or ignore into book values (12, 'Financial Accounting', 'Robert Libby and Patricia Libby', '7th', 5223);
insert or ignore into book values (13, 'Financial Accounting: Tools for Business Decision Making', 'Paul D. Kimmel and Jerry J. Weygandt', '9th', 5224);
insert or ignore into book values (14, 'Systems Analysis and Design', 'Alan Dennis', '6th', 3253);
insert or ignore into book values (15, 'Internet Marketing: The Definitive Beginner Guide', 'Adam Richards', '4th', 5232);
insert or ignore into book values (16, 'Digital Marketing Analytics', 'Chuck Hemann and Ken Burbary', '5th', 42332);
insert or ignore into book values (17, 'Mining the Social Web', 'Matthew A. Russell', '5th', 5423);
insert or ignore into book values (18, 'Marketing Analytics', 'Wayne L. Winston', '10th', 5343);
insert or ignore into book values (19, 'The Complete Guide to Direct Marketing', 'Chet Meisner', '5th', 6233);
insert or ignore into book values (20, 'Direct Marketing: Strategy, Planning, Execution', 'Edward Nash', '6th', 3453);
insert or ignore into book values (21, 'Real Estate Marketing in the 21st Century', 'William Johnson', '5th', 4242);
insert or ignore into book values (22, 'Real Estate Marketing in the 21st Century', 'Ameen Kamadia', '4th', 6234);
insert or ignore into course_book values (1, 1, 1);
insert or ignore into course_book values (2, 1, 2);
insert or ignore into course_book values (3, 1, 3);
insert or ignore into course_book values (4, 2, 4);
insert or ignore into course_book values (5, 2, 5);
insert or ignore into course_book values (6, 3, 6);
insert or ignore into course_book values (7, 4, 7);
insert or ignore into course_book values (8, 4, 8);
insert or ignore into course_book values (9, 5, 9);
insert or ignore into course_book values (10, 5, 10);
insert or ignore into course_book values (11, 5, 11);
insert or ignore into course_book values (12, 6, 12);
insert or ignore into course_book values (13, 6, 13);
insert or ignore into course_book values (14, 7, 14);
insert or ignore into course_book values (15, 8, 15);
insert or ignore into course_book values (16, 9, 16);
insert or ignore into course_book values (17, 9, 17);
insert or ignore into course_book values (18, 9, 18);
insert or ignore into course_book values (19, 10, 19);
insert or ignore into course_book values (20, 10, 20);
insert or ignore into course_book values (21, 11, 21);
insert or ignore into course_book values (22, 11, 22);
