---
# Config  for my application
# --------------------------
myapp:
  foo: bar
  bar: [1, 2]

# Config for logging
# ------------------
# See http://docs.python.org/2.7/library/logging.config.html#configuration-dictionary-schema

logging:
  version: 1
  disable_existing_loggers: true

  # Configuring the default (root) logger is highly recommended

  root:
    level: !!python/name:logging.NOTSET
    handlers: [console]

  loggers:

    # Logging from my application
    bookz:
      level: !!python/name:logging.WARN
      handlers: [logfile]
      qualname: bookz
      propagate: false
    # Controlling logging of 3rd party libs

    sqlalchemy.engine:
      level: !!python/name:logging.WARN
      handlers: [logfile]
      qualname: sqlalchemy.engine
      propagate: false
    sqlalchemy.pool:
      level: !!python/name:logging.WARN
      handlers: [logfile]
      qualname: sqlalchemy.pool
      propagate: false

  handlers:
    logfile:
      class: logging.RotatingFileHandler
      filename: /var/log/bookz/bookz.log
      formatter: simpleFormatter
      level: !!python/name:logging.NOTSET

  formatters:
    simpleFormatter:
      class: !!python/name:logging.Formatter
      format: '%(name)s %(asctime)s %(levelname)s %(message)s'
      datefmt: '%d/%m/%Y %H:%M:%S'