---
# Config for logging
# ------------------
# See http://docs.python.org/2.7/library/logging.config.html#configuration-dictionary-schema

logging:
  version: 1
  disable_existing_loggers: false

  # Configuring the default (root) logger is highly recommended

  root:
    level: !!python/name:logging.NOTSET
    handlers: [logfile, debug_logfile]

  handlers:
    logfile:
      class: logging.handlers.RotatingFileHandler
      level: INFO
      formatter: simpleFormatter
      filename: /var/log/bookz/bookz.log
      maxBytes: 10485760 # 10MB
      backupCount: 20
      encoding: utf8
    debug_logfile:
      class: logging.handlers.RotatingFileHandler
      level: DEBUG
      filename: /var/log/bookz/bookz_debug.log
      formatter: simpleFormatter
      maxBytes: 10485760 # 10MB
      backupCount: 10
      encoding: utf8

  formatters:
    simpleFormatter:
      class: !!python/name:logging.Formatter
      format: '%(name)s %(asctime)s %(levelname)s %(message)s'
      datefmt: '%d/%m/%Y %H:%M:%S'